import * as Print from "expo-print";
import * as Sharing from "expo-sharing";

export type RevenuePdfInput = {
  organizerName: string;
  asOfLabel: string;
  summary: {
    grossRevenue: number;
    platformFee: number;
    eligiblePayout: number;
    realPayments: number;
    couponPayments: number;
    freeCoupons: number;
    freeCouponFaceValue: number;
    totalPaidOut: number;
    availableBalance: number;
  };
  trips: Array<{
    tripTitle: string;
    totalBookings: number;
    grossAmount: number;
    eligibleAmount: number;
  }>;
  transactions: Array<{
    paidAt: string;
    memberName: string;
    tripTitle: string;
    grossAmount: number;
    amountPaid: number;
    type: string;
  }>;
};

function esc(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

function money(n: number): string {
  return `₹${Number(n || 0).toLocaleString("en-IN", { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
}

export function buildRevenueSummaryHtml(data: RevenuePdfInput): string {
  const s = data.summary;
  const rows = data.transactions
    .map(
      (t) =>
        `<tr><td>${esc(t.paidAt)}</td><td>${esc(t.memberName)}</td><td>${esc(t.tripTitle)}</td><td>${money(t.grossAmount)}</td><td>${money(t.amountPaid)}</td><td>${esc(t.type)}</td></tr>`,
    )
    .join("");

  const tripRows = data.trips
    .map(
      (t) =>
        `<tr><td>${esc(t.tripTitle)}</td><td>${t.totalBookings}</td><td>${money(t.grossAmount)}</td><td>${money(t.eligibleAmount)}</td></tr>`,
    )
    .join("");

  return `<!DOCTYPE html>
<html><head><meta charset="utf-8"/><style>
body{font-family:system-ui,-apple-system,sans-serif;background:#fff;color:#111;padding:24px;font-size:12px;}
h1{font-size:20px;margin:0 0 8px;}
h2{font-size:14px;margin:24px 0 8px;color:#333;}
.muted{color:#666;font-size:11px;}
table{width:100%;border-collapse:collapse;margin-top:8px;}
th,td{border:1px solid #ddd;padding:6px 8px;text-align:left;}
th{background:#f5f5f5;font-size:11px;}
.footer{margin-top:32px;font-size:10px;color:#999;}
</style></head><body>
<div style="font-weight:800;font-size:18px;">Trip-Sync</div>
<h1>Revenue summary</h1>
<p class="muted">Organizer: ${esc(data.organizerName)} · As of ${esc(data.asOfLabel)}</p>

<h2>Summary</h2>
<table>
<tr><th>Metric</th><th>Amount</th></tr>
<tr><td>Gross revenue (cash)</td><td>${money(s.grossRevenue)}</td></tr>
<tr><td>Platform fee (10%)</td><td>${money(s.platformFee)}</td></tr>
<tr><td>Real payments</td><td>${money(s.realPayments)}</td></tr>
<tr><td>Coupon payments</td><td>${money(s.couponPayments)}</td></tr>
<tr><td>Free coupons (bookings)</td><td>${s.freeCoupons} (${money(s.freeCouponFaceValue)} face value)</td></tr>
</table>

<h2>Trip breakdown</h2>
<table>
<tr><th>Trip</th><th>Bookings</th><th>Gross</th><th>Eligible</th></tr>
${tripRows}
</table>

<h2>Transactions</h2>
<table>
<tr><th>Date</th><th>Member</th><th>Trip</th><th>Gross</th><th>Paid</th><th>Type</th></tr>
${rows}
</table>

<p class="footer">Generated by Trip-Sync · Confidential</p>
</body></html>`;
}

export async function shareRevenuePdf(html: string): Promise<void> {
  const { uri } = await Print.printToFileAsync({
    html,
    base64: false,
  });
  try {
    await Sharing.shareAsync(uri, {
      mimeType: "application/pdf",
      dialogTitle: "Trip-Sync — Export PDF",
      UTI: "com.adobe.pdf",
    });
  } catch (err) {
    const can = await Sharing.isAvailableAsync();
    if (!can) {
      throw new Error("Sharing is not available on this device.");
    }
    throw err instanceof Error ? err : new Error(String(err));
  }
}

export function buildPayoutHistoryHtml(rows: Array<Record<string, unknown>>, organizerName: string, asOf: string): string {
  const body = rows
    .map((r) => {
      const amt = money(Number(r.amount ?? 0));
      const st = esc(String(r.status ?? ""));
      const via = esc(String(r.payout_method_snapshot ?? ""));
      const req = esc(String(r.requested_at ?? "").slice(0, 10));
      const proc = r.processed_at ? esc(String(r.processed_at).slice(0, 10)) : "—";
      return `<tr><td>${amt}</td><td>${st}</td><td>${via}</td><td>${req}</td><td>${proc}</td></tr>`;
    })
    .join("");
  return `<!DOCTYPE html><html><head><meta charset="utf-8"/><style>
body{font-family:system-ui,sans-serif;padding:24px;font-size:12px;}
table{width:100%;border-collapse:collapse;} th,td{border:1px solid #ddd;padding:8px;text-align:left;}
</style></head><body>
<h1>Trip-Sync — Payout history</h1>
<p>${esc(organizerName)} · ${esc(asOf)}</p>
<table><tr><th>Amount</th><th>Status</th><th>Method</th><th>Requested</th><th>Processed</th></tr>${body}</table>
</body></html>`;
}
